### PR TITLE
Merge upstream: Checkout for logged in BC users, API version update.

### PR DESCRIPTION
**Pull request by garrow**
Need to add 
```
BIGCOMMERCE_STORE_URL=
BIGCOMMERCE_STORE_API_STORE_HASH=
BIGCOMMERCE_STORE_API_CLIENT_SECRET=
```

### CODE REVIEW

**Comment by garrow** [comment]
Testing when attempting to checkout as a logged in user.

image


```
{
	"id": "AQAAAXqBRlFU3uLd7AAAAABBWHFCUm1FUEFBQ0NNdHN5ZDEzOEdnQUE",
	"content": {
		"timestamp": "2021-07-07T14:01:47.092Z",
		"tags": [
			"source:vercel"
		],
		"host": "optics-unlimited-furr6d01d-opticsunlimited.vercel.app",
		"message": "START RequestId: 328e8da5-bfa2-4584-afb1-ca0bcf374ad4 Version: $LATEST\n2021-07-07T14:01:47.522Z\t328e8da5-bfa2-4584-afb1-ca0bcf374ad4\tERROR\tError: secretOrPrivateKey must have a value\n    at Object.module.exports [as sign] (/var/task/node_modules/jsonwebtoken/sign.js:107:20)\n    at Object.checkout_checkout [as checkout] (/var/task/.next/server/pages/api/checkout.js:157:49)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.checkoutEndpoint [as handler] (/var/task/.next/server/pages/api/checkout.js:85:12)\n    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)\n    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:66:462)\n    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:58:580)\n    at async Router.execute (/var/task/node_modules/next/dist/next-server/server/router.js:25:67)\n    at async Server.run (/var/task/node_modules/next/dist/next-server/server/next-server.js:68:1042)\n    at async Server.handleRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:32:504)\nEND RequestId: 328e8da5-bfa2-4584-afb1-ca0bcf374ad4\nREPORT RequestId: 328e8da5-bfa2-4584-afb1-ca0bcf374ad4\tDuration: 416.11 ms\tBilled Duration: 417 ms\tMemory Size: 1024 MB\tMax Memory Used: 95 MB",
		"attributes": {
			"path": "en-US/api/checkout",
			"deploymentId": "dpl_91m6h1omkWhYe9H6Q8RKet8kTz22",
			"source": "lambda",
			"projectId": "prj_AiucPTinO7KFn5uCUTsf8i6e1zTv",
			"host": "optics-unlimited-furr6d01d-opticsunlimited.vercel.app",
			"proxy": {
				"timestamp": 1625666507087,
				"region": "iad1",
				"host": "optics-unlimited-furr6d01d-opticsunlimited.vercel.app",
				"referer": "https://optics-unlimited-furr6d01d-opticsunlimited.vercel.app/product/fog-linen-chambray-towel-beige-stripe",
				"userAgent": [
					"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
				],
				"path": "/checkout",
				"clientIp": "68.175.35.37",
				"scheme": "https",
				"method": "GET",
				"statusCode": 500
			},
			"timestamp": 1625666507092,
			"statusCode": 500,
			"id": "1625666507092965975717252612",
			"requestId": "2qffm-1625666507087-253d46796e6e"
		}
	}
}
```

**Comment by gje4** [comment]
> Testing when attempting to checkout as a logged in user.
> 
> image
> 
> ```
> {
> 	"id": "AQAAAXqBRlFU3uLd7AAAAABBWHFCUm1FUEFBQ0NNdHN5ZDEzOEdnQUE",
> 	"content": {
> 		"timestamp": "2021-07-07T14:01:47.092Z",
> 		"tags": [
> 			"source:vercel"
> 		],
> 		"host": "optics-unlimited-furr6d01d-opticsunlimited.vercel.app",
> 		"message": "START RequestId: 328e8da5-bfa2-4584-afb1-ca0bcf374ad4 Version: $LATEST\n2021-07-07T14:01:47.522Z\t328e8da5-bfa2-4584-afb1-ca0bcf374ad4\tERROR\tError: secretOrPrivateKey must have a value\n    at Object.module.exports [as sign] (/var/task/node_modules/jsonwebtoken/sign.js:107:20)\n    at Object.checkout_checkout [as checkout] (/var/task/.next/server/pages/api/checkout.js:157:49)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.checkoutEndpoint [as handler] (/var/task/.next/server/pages/api/checkout.js:85:12)\n    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)\n    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:66:462)\n    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:58:580)\n    at async Router.execute (/var/task/node_modules/next/dist/next-server/server/router.js:25:67)\n    at async Server.run (/var/task/node_modules/next/dist/next-server/server/next-server.js:68:1042)\n    at async Server.handleRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:32:504)\nEND RequestId: 328e8da5-bfa2-4584-afb1-ca0bcf374ad4\nREPORT RequestId: 328e8da5-bfa2-4584-afb1-ca0bcf374ad4\tDuration: 416.11 ms\tBilled Duration: 417 ms\tMemory Size: 1024 MB\tMax Memory Used: 95 MB",
> 		"attributes": {
> 			"path": "en-US/api/checkout",
> 			"deploymentId": "dpl_91m6h1omkWhYe9H6Q8RKet8kTz22",
> 			"source": "lambda",
> 			"projectId": "prj_AiucPTinO7KFn5uCUTsf8i6e1zTv",
> 			"host": "optics-unlimited-furr6d01d-opticsunlimited.vercel.app",
> 			"proxy": {
> 				"timestamp": 1625666507087,
> 				"region": "iad1",
> 				"host": "optics-unlimited-furr6d01d-opticsunlimited.vercel.app",
> 				"referer": "https://optics-unlimited-furr6d01d-opticsunlimited.vercel.app/product/fog-linen-chambray-towel-beige-stripe",
> 				"userAgent": [
> 					"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
> 				],
> 				"path": "/checkout",
> 				"clientIp": "68.175.35.37",
> 				"scheme": "https",
> 				"method": "GET",
> 				"statusCode": 500
> 			},
> 			"timestamp": 1625666507092,
> 			"statusCode": 500,
> 			"id": "1625666507092965975717252612",
> 			"requestId": "2qffm-1625666507087-253d46796e6e"
> 		}
> 	}
> }
> ```

Did you add in the env variable to vercel or to your local env file.

BIGCOMMERCE_STORE_URL=
BIGCOMMERCE_STORE_API_STORE_HASH=
BIGCOMMERCE_STORE_API_CLIENT_SECRET=

**Comment by garrow** [comment]
I got this error when I am **sure** I am logged in.
on 
https://optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app

image

**Comment by garrow** [comment]
Need to handle the not logged in case, but the commerce app thinks we are still logged in.

See
image

```
{
    "data": null,
    "errors": [
        {
            "message": "Customer not found",
            "code": "not_found"
        }
    ]
}
```

**Comment by garrow** [comment]
While logged out, I got this wishlist error, but this is not the one that related to the checkout failure.
```
{
	"id": "AQAAAXqGyfGammuhKQAAAABBWHFHeWZ1ZUFBQlBEZHNkREZoa0VBQUI",
	"content": {
		"timestamp": "2021-07-08T15:43:39.418Z",
		"tags": [
			"source:vercel"
		],
		"host": "optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app",
		"message": "START RequestId: 1cb4f7fb-c5b7-4615-ae44-00d02b2f456e Version: $LATEST\n2021-07-08T15:43:39.713Z\t1cb4f7fb-c5b7-4615-ae44-00d02b2f456e\tERROR\tBigcommerceApiError: Big Commerce API error (422) \nHeaders: {\n  \"connection\": \"keep-alive\",\n  \"content-encoding\": \"gzip\",\n  \"content-type\": \"application/json\",\n  \"strict-transport-security\": \"max-age=31536000; includeSubDomains\",\n  \"transfer-encoding\": \"chunked\",\n  \"vary\": \"Accept-Encoding\",\n  \"x-rate-limit-requests-left\": \"16101486\",\n  \"x-rate-limit-requests-quota\": \"16101495\",\n  \"x-rate-limit-time-reset-ms\": \"12949\",\n  \"x-rate-limit-time-window-ms\": \"30000\",\n  \"x-request-id\": \"abae8df035d8e5e6eb30a3139d497c4b\"\n}\n{\n  \"status\": 422,\n  \"title\": \"JSON data is missing or invalid\",\n  \"type\": \"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes\",\n  \"errors\": {\n    \"customer_id\": \"error.expected.jsnumber\"\n  }\n}\n    at Object.storeApiFetch (/var/task/.next/server/chunks/862.js:484:11)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.addItem (/var/task/.next/server/pages/api/wishlist.js:273:94)\n    at async Object.wishlistEndpoint [as handler] (/var/task/.next/server/pages/api/wishlist.js:130:14)\n    at async apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:1)\n    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:66:462)\n    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:58:580)\n    at async Router.execute (/var/task/node_modules/next/dist/next-server/server/router.js:25:67)\n    at async Server.run (/var/task/node_modules/next/dist/next-server/server/next-server.js:68:1042)\n    at async Server.handleRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:32:504) {\n  status: 422,\n  res: Response {\n    size: 0,\n    timeout: 0,\n    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },\n    [Symbol(Response internals)]: {\n      url: 'https://35.227.219.245/stores/rpst6qbqw/v3/wishlists',\n      status: 422,\n      statusText: 'Unprocessable Entity',\n      headers: [Headers],\n      counter: 0\n    },\n    [Symbol(dnsCachedUrl)]: 'https://35.227.219.245/stores/rpst6qbqw/v3/wishlists'\n  },\n  data: {\n    status: 422,\n    title: 'JSON data is missing or invalid',\n    type: 'https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes',\n    errors: { customer_id: 'error.expected.jsnumber' }\n  }\n}\nEND RequestId: 1cb4f7fb-c5b7-4615-ae44-00d02b2f456e\nREPORT RequestId: 1cb4f7fb-c5b7-4615-ae44-00d02b2f456e\tDuration: 275.94 ms\tBilled Duration: 276 ms\tMemory Size: 1024 MB\tMax Memory Used: 92 MB",
		"attributes": {
			"path": "en-US/api/wishlist",
			"deploymentId": "dpl_H53c6RjGF7ZayoNiTmQC8GKJppdQ",
			"source": "lambda",
			"projectId": "prj_AiucPTinO7KFn5uCUTsf8i6e1zTv",
			"host": "optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app",
			"proxy": {
				"timestamp": 1625759019418,
				"region": "iad1",
				"host": "optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app",
				"referer": "https://optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app/product/orbit-terrarium-large",
				"userAgent": [
					"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
				],
				"path": "/api/wishlist",
				"clientIp": "68.175.35.37",
				"scheme": "https",
				"method": "POST",
				"statusCode": 500
			},
			"timestamp": 1625759019418,
			"statusCode": 500,
			"id": "1625759019418164709100342303",
			"requestId": "l55wb-1625759019418-5984ccba3029"
		}
	}
}
```

**Comment by garrow** [comment]
This is a redirect that failed to keep me logged in.

```json
{
	"id": "AQAAAXqG-del3rn1jAAAAABBWHFHLWVQTkFBQ1g2VFdIU0x5YTJBQUE",
	"content": {
		"timestamp": "2021-07-08T16:35:58.501Z",
		"tags": [
			"source:vercel"
		],
		"host": "optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app",
		"message": "START RequestId: 5dc3be4f-4b66-4e52-a915-c05751a34c96 Version: $LATEST\n2021-07-08T16:35:59.189Z\t5dc3be4f-4b66-4e52-a915-c05751a34c96\tINFO\tcheckouturl https://optics-sandbox.mybigcommerce.com/login/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3Y3phYTRudWRlcDVnYzZyZTBlbHJzeGpjZDFlbHIxIiwiaWF0IjoxNjI1NzYyMTU5LCJqdGkiOiJiYTA1MzczYS0zNTQ2LTQ3ZjQtODliNy02NzE2OTRiOGU3ODAiLCJvcGVyYXRpb24iOiJjdXN0b21lcl9sb2dpbiIsInN0b3JlX2hhc2giOiJycHN0NnFicXciLCJjdXN0b21lcl9pZCI6IjIyIiwiY2hhbm5lbF9pZCI6IjcxNDg4NyIsInJlZGlyZWN0X3RvIjoiaHR0cHM6Ly9vcHRpY3Mtc2FuZGJveC5teWJpZ2NvbW1lcmNlLmNvbS9jYXJ0LnBocD9hY3Rpb249bG9hZEluQ2hlY2tvdXQmaWQ9ODllZDllODctYWNlYi00OTJlLTgzNDQtNDhlZjk5YWQ0Y2UwJnRva2VuPWZiYTU0Zjg1Y2Q1NWNlZDVhMTExNWMwYWEwMDYxYjAwZWRjOWFiYWUwNmJiNDM3NDI4MmI2OTlhYzY5NTZjYzIifQ.TXhBbmtI-EZfQ4WTD4dYFBqHR3urhdxZTywRu3uJWjU\n2021-07-08T16:35:59.190Z\t5dc3be4f-4b66-4e52-a915-c05751a34c96\tERROR\t(node:8) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.\n(Use `node --trace-deprecation ...` to show where the warning was created)\nEND RequestId: 5dc3be4f-4b66-4e52-a915-c05751a34c96\nREPORT RequestId: 5dc3be4f-4b66-4e52-a915-c05751a34c96\tDuration: 662.76 ms\tBilled Duration: 663 ms\tMemory Size: 1024 MB\tMax Memory Used: 94 MB",
		"attributes": {
			"path": "en-US/api/checkout",
			"deploymentId": "dpl_H53c6RjGF7ZayoNiTmQC8GKJppdQ",
			"statusCode": 307,
			"proxy": {
				"statusCode": 307,
				"timestamp": 1625762158494,
				"region": "iad1",
				"host": "optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app",
				"referer": "https://optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app/",
				"userAgent": [
					"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
				],
				"path": "/checkout",
				"clientIp": "68.175.35.37",
				"scheme": "https",
				"method": "GET"
			},
			"source": "lambda",
			"projectId": "prj_AiucPTinO7KFn5uCUTsf8i6e1zTv",
			"host": "optics-unlimited-mm5kjak9q-opticsunlimited.vercel.app",
			"timestamp": 1625762158501,
			"id": "1625762158501543229483478103",
			"requestId": "prdgk-1625762158494-70ecb3e601ce"
		}
	}
}

```

**Comment by gje4** [comment]
Not sure how it happen, but i most likely did it.  It appears our client_id was wrong.  I have updated the env and redeployed.  Issues seem to be resolved.

**Pull request merged**
